name: everex_function_test
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5
  camera: ^0.10.3
  native_device_orientation: ^1.1.4
  dio: ^4.0.4                   # Http 통신
  image_picker: ^0.8.5+3
  everex_tflite:
    git:
      url: https://github.com/TeamEverExDev/EverexTflite.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
